services:
  - type: web
    name: bybit-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: API_KEY
        value: O6o45ugAjaA9DIOpYU
      - key: API_SECRET
        value: DBA3RWkisO9mYVUT0UdhMqj8QwTbbYrbyXcX
      - key: PASS_PHRASE
        value: mysecret
